### ISSUE TITLE
[performance-testing-cli] Promise on exec is not rejected

### ISSUE THREAD

**Issue by JulienBlacas** [keiya01/react-performance-testing#20]
Hi @keiya01,

Thank you for this library. It looks to me that the promise in `packages/performance-testing-cli/src/exec.ts` should be rejected if the child process returns with an error, as such : 

```ts
import child_process from 'child_process';
import { logError } from './logger';

export const exec = (cmd: string, filepath: string, args: string[]) => {
  return new Promise((resolve, reject) => {
    const { error } = child_process.spawnSync(cmd, [filepath, ...args], {
      stdio: 'inherit',
      env: { ...process.env },
    });

    if (error) {
      logError(error);
      return reject(error);
    }
    return resolve();
  });
};

```

Because of that, our CircleCi pipeline never fail even if some jest tests fails.

Can I open a fix PR for that issue ?

**Comment by keiya01** [comment]
@JulienBlacas 
> Can I open a fix PR for that issue ?

Thank you for reporting issue.
You can open PR. Thank you :)
